version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/code_pipeline_lightsail_django_test
permissions:
   - object: /home/ubuntu/code_pipeline_lightsail_django_test
     pattern: "**"
     owner: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
